version: "3.0"

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        restart: always
        environment:
          ZOOKEEPER_SERVER_ID: 1
          ZOOKEEPER_CLIENT_PORT: "2181"
          ZOOKEEPER_TICK_TIME: "2000"
        ports:
          - "2181:2181"
    kafka:
        image: confluentinc/cp-enterprise-kafka:latest
        depends_on:
          - zookeeper
        ports:
          - "29092:29092"
          - "9092:9092"
        environment:
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
          KAFKA_BROKER_ID: 1
          KAFKA_BROKER_RACK: "r1"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_DELETE_TOPIC_ENABLE: "true"
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
          KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8081"
          
    schemaregistry:
        image: confluentinc/cp-schema-registry:5.2.1
        restart: always
        depends_on:
          - zookeeper
        environment:
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
          SCHEMA_REGISTRY_HOST_NAME: schemaregistry
          SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
        ports:
          - "8081:8081"
    schema_registry_ui:
        image: landoop/schema-registry-ui:0.9.4
        hostname: schema_registry_ui
        ports:
          - "8000:8000"
        environment:
          SCHEMAREGISTRY_URL: http://schema_registry:8081
          PROXY: 'true'
        depends_on:
          - schema_registry
      rest_proxy:
        image: confluentinc/cp-kafka-rest:latest
        hostname: rest_proxy
        depends_on:
          - schema_registry
          - kafka
        ports:
          - "7082:8082"
        environment:
          KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_REST_LISTENERS: http://rest_proxy:8082
          KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema_registry:8081
          KAFKA_REST_HOST_NAME: rest_proxy
          KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
          KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 30000
          KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'
          KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGN: '*'
    
    